accounts/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from .views import RegisterView, UserView

app_name = 'accounts'

urlpatterns = [
    path("<int:pk>/", UserView.as_view(), name="user_view"),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name='registration'),
]

exam10/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exam10 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, AdvertisementCreateView, AdvertisementUpdateView, AdvertisementView, \
    AdvertisementDeleteView, ModerateIndexView, ModerateUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('advertisement/create/', AdvertisementCreateView.as_view(), name='advertisement_create'),
    path('advertisement/<int:pk>/update/', AdvertisementUpdateView.as_view(), name='advertisement_update'),
    path('advertisement/<int:pk>/', AdvertisementView.as_view(), name='advertisement_view'),
    path('advertisement/<int:pk>/delete/', AdvertisementDeleteView.as_view(), name='advertisement_delete'),
    path('moderator/advertisement/', ModerateIndexView.as_view(), name='moderator_advertisement_list'),
    path('moderator/advertisement/<int:pk>/', ModerateUpdateView.as_view(), name='moderator_advertisement'),
]

accounts/models.py
# from django.contrib.auth import get_user_model
# from django.db import models
# from phonenumber_field.modelfields import PhoneNumberField
# User = get_user_model()
#
#
# class OwnUser(User):
#     number = PhoneNumberField

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
CHOICES = [('InModiration', 'На Модерацию'), ('Rejected', 'Отклонено'),('Publiced', 'Опубликована')]


class Advertisement(models.Model):
    photo = models.ImageField(verbose_name="Фотография ", upload_to="photos/", null=False, blank=False)
    caption = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок')
    text = models.TextField(max_length=1000, null=False, blank=False, verbose_name='Текст')
    price = models.IntegerField(verbose_name='Цена', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    last_update = models.DateTimeField(auto_now=True, verbose_name="Время обновления")
    publicated_at = models.DateTimeField(auto_now=True, verbose_name="Время публикации")

    author = models.ForeignKey(
        User,
        related_name="advertisements",
        verbose_name="Автор",
        on_delete=models.CASCADE,
    )
    status = models.CharField(max_length=100, verbose_name='Статус', choices=CHOICES, default=CHOICES[0][0])

    def __str__(self):
        return f"{self.pk}. {self.caption}: {self.text}"

    class Meta:
        db_table = 'advertisement'
        verbose_name = 'Обьявление'
        verbose_name_plural = "Обьявления"
        permissions = [
            (
                'staff',
                'делает все',
            )
        ]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ("username", "password1", "password2", "email", "first_name", "last_name")

    def clean_email(self):
        if self.cleaned_data.get("email") == '':
            raise ValidationError("Введите свою почту")
        return self.cleaned_data.get("email")

webapp/forms.py
from django import forms
from webapp.models import Advertisement


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        exclude = ['created_at', 'last_update', 'publicated_at', 'author', 'status']


class ModeratorForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ['status']

accounts/views.py
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, CreateView

from .forms import MyUserCreationForm

User = get_user_model()


class UserView(DetailView):
    model = get_user_model()
    template_name = "user_view.html"
    context_object_name = "user_object"

    def get_context_data(self, **kwargs):
        context = super(UserView, self).get_context_data()
        advertisements = self.object.advertisements.filter(status='Publiced')
        print(advertisements)
        context['advertisements'] = advertisements
        return context


class RegisterView(CreateView):
    model = User
    form_class = MyUserCreationForm
    template_name = "registration.html"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url

webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from .forms import AdvertisementForm, ModeratorForm
from .models import Advertisement


class IndexView(ListView):
    model = Advertisement
    template_name = "advertisement/index.html"
    ordering = ['-publicated_at']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data()
        advertisements = Advertisement.objects.filter(status='Publiced')
        context['advertisements'] = advertisements
        return context


class ModerateIndexView(PermissionRequiredMixin,ListView):
    model = Advertisement
    template_name = "advertisement/moderate_index.html"
    ordering = ['-created_at']
    permission_required = 'webapp.staff'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ModerateIndexView, self).get_context_data()
        advertisements = Advertisement.objects.filter(status='InModiration')
        context['advertisements'] = advertisements
        return context


class AdvertisementView(DetailView):
    model = Advertisement
    template_name = 'advertisement/view.html'


class AdvertisementCreateView(LoginRequiredMixin,CreateView):
    model = Advertisement
    template_name = 'advertisement/create.html'
    form_class = AdvertisementForm
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.add_advertisement'

    def form_valid(self, form):
        advertisement = form.save(commit=False)
        advertisement.author = self.request.user
        advertisement.save()
        return redirect('webapp:index')


class ModerateUpdateView(PermissionRequiredMixin, UpdateView):
    model = Advertisement
    form_class = ModeratorForm
    template_name = 'advertisement/update.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.staff'


class AdvertisementUpdateView(PermissionRequiredMixin, UpdateView):
    model = Advertisement
    form_class = AdvertisementForm
    template_name = 'advertisement/update.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.change_advertisement'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.object.author


class AdvertisementDeleteView(PermissionRequiredMixin, DeleteView):
    model = Advertisement
    template_name = 'advertisement/delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_advertisement'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.object.author

accounts/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h1>Вход</h1>
    <form method="post" class="text-center ms-auto me-auto w-50">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <button class="mt-3 btn btn-primary" type="submit">Войти</button>
    </form>
{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <form method="post">
        {% include "partial/form.html" with button_text="Зарегистрироваться" %}
    </form>
{% endblock %}

accounts/templates/user_view.html
{% extends "base.html" %}

{% block nav %}
{% endblock nav %}
{% block content %}
    <h1>Логин: {{ user_object.username}}</h1>
    <h2>Имя и фамилия пользователя: {{ user_object.firs_name }} {{ user_object.last_name }}</h2>
    <h2>Email: {{ user_object.email }}</h2>
        {% for advertisement in advertisements %}
        <div class="card" style="width: 18rem;">
             {% if advertisement.photo %}
                    <img src="{{ advertisement.photo.url }}" alt="photo photo">
            {% else %}
                <img src='https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg' class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <p>Дата: {{ advertisement.created_at }}</p>
                    {% if perms.webapp.change_advertisement or user == advertisement.author %}
                        <a href="{% url 'webapp:advertisement_update' advertisement.pk %}" class="btn btn-primary">Изменить обьявление</a>
                    {% endif %}
                    {% if perms.webapp.delete_advertisement or user == advertisement.author %}
                        <a href="{% url 'webapp:advertisement_delete' advertisement.pk %}" class="btn btn-primary">Удалить обьявление</a>
                    {% endif %}
                        <a href="{% url 'webapp:advertisement_view' advertisement.pk %}" class="btn btn-primary">Посмотреть обьявление</a>
            </div>
        </div>

        -------------------------------------------
        {% endfor %}
{% endblock content %}

webapp/templates/advertisement/create.html
{% extends 'base.html' %}

{% block title %}Create advertisement{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <h1>Добавить обьявление</h1>

    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Добавить" %}
    </form>

{% endblock %}

webapp/templates/advertisement/delete.html
{% extends "base.html" %}

{% block content %}
    <form action="{% url 'webapp:advertisement_delete' advertisement.pk %}" method="POST">
    {% csrf_token %}
        <h2>Вы действительно хотите удалить обьявление?</h2>
        <input type="submit" value="Да">
    </form>
    <form action="{% url "webapp:index" %}" target="_blank">
        <button>Нет</button>
    </form>
{% endblock %}

webapp/templates/advertisement/index.html
{% extends 'base.html' %}
{% block nav %}
    {% if user.is_authenticated %}
         <li class="nav-item">
             <a class="nav-link" href="{% url 'webapp:advertisement_create' %}">Добавить обьявление</a>
         </li>
    {% endif %}
{% endblock %}
{% block content%}
    {% for advertisement in advertisements %}
        <div class="card" style="width: 18rem;">
             {% if advertisement.photo %}
                    <img src="{{ advertisement.photo.url }}" alt="photo photo">
            {% else %}
                <img src='https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg' class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <p>Дата: {{ advertisement.created_at }}</p>
                    {% if perms.webapp.change_advertisement or user == advertisement.author %}
                        <a href="{% url 'webapp:advertisement_update' advertisement.pk %}" class="btn btn-primary">Изменить обьявление</a>
                    {% endif %}
                    {% if perms.webapp.delete_advertisement or user == advertisement.author %}
                        <a href="{% url 'webapp:advertisement_delete' advertisement.pk %}" class="btn btn-primary">Удалить обьявление</a>
                    {% endif %}
                        <a href="{% url 'webapp:advertisement_view' advertisement.pk %}" class="btn btn-primary">Посмотреть обьявление</a>
            </div>
        </div>

    {% endfor %}
{% endblock content%}

webapp/templates/advertisement/moderate_index.html
{% extends 'base.html' %}
{% block nav %}

{% endblock %}
{% block content%}
    {% for advertisement in advertisements %}
        <div class="card" style="width: 18rem;">
             {% if advertisement.photo %}
                    <img src="{{ advertisement.photo.url }}" alt="photo photo">
            {% else %}
                <img src='https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg' class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
{#                <a href="{% url 'accounts:user_view' advertisement.author.pk  %}" class="card-text">Автор: {{ advertisement.author }}</a>#}
                <p>Дата: {{ advertisement.created_at }}</p>
                {% if perms.webapp.staff %}
                    <a href="{% url 'webapp:moderator_advertisement' advertisement.pk %}" class="btn btn-primary">Посмотреть обьявление</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock content%}

webapp/templates/advertisement/update.html
{% extends 'base.html' %}

{% block title %}Изменить Обьявление{% endblock %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:advertisement_view' advertisement.pk%}">Просмотр обьявления</a>
    </li>{% endblock %}
{% block content %}
    <h1>Изменить обьявление</h1>
    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Изменить"  %}
    </form>

{% endblock %}

webapp/templates/advertisement/view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Advertisement{{ advertisement.pk }}{% endblock %}
          {% block nav %}
            {% if perms.webapp.add_advertisement %}
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'webapp:advertisement_create' %}">Добавить обьявление</a>
                 </li>
            {% endif %}
              {% if perms.webapp.change_advertisement or user == advertisement.author %}
                  <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "webapp:advertisement_update" advertisement.pk %}">Изменить обьявление</a>
                  </li>
              {% endif %}
              {% if  perms.webapp.delete_advertisement or user == advertisement.author %}
                  <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'webapp:advertisement_delete' advertisement.pk %}">Удалить обьявление</a>
                  </li>
              {% endif %}
            {% endblock %}
    {% block content %}
        <div class="card" style="width: 18rem;">
            <ul class="list-group list-group-flush">
                {% if advertisement.photo %}
                    <img src="{{ advertisement.photo.url }}" alt="photo photo">
                {% else %}
                    <img src='https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg' class="card-img-top" alt="...">
                {% endif %}
                <li class="list-group-item">Заголовок обьявления: {{ advetisement.caption }}</li>
                <li class="list-group-item"><a href="{% url 'accounts:user_view' advertisement.author.pk  %}" class="card-text">Автор: {{ advertisement.author }}</a></li>
                <li class="list-group-item">Дата: {{ advertisement.created_at }}</li>
            </ul>
        </div>

    {% endblock content%}

webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}List articles{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href={% url 'webapp:index' %}>Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if perms.webapp.staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:moderator_advertisement_list' %}">Список обьявлений для модерации</a>
                    </li>
                {% endif %}
                {% block nav %}
                {% endblock %}
                {% if not user.is_authenticated %}
                {% if request.path == '/accounts/registration/'%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Вход</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a>
                    </li>
                {% endif %}
                    {% if request.path == '/accounts/login/'%}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:registration' %}">Регистрация</a>
                        </li>
                {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:registration' %}?next={{ request.get_full_path }}">Регистрация</a>
                     </li>
                {% endif %}

                {% else %}
                                            <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Выход </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_view' user.id %}">Пользователь: {{ user.username }}</a>
                </li>
                        {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
</script>

{% block scripts %}{% endblock scripts %}
</body>
</html>

webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {{ field }}
{% endfor %}

<br>
<input type="submit" value={{ button_text }} />